[metadata]
version = "1.0"

[versions]

# platforms
java = "17"
mindustry = "v146"

# logging
slf4j = "2.0.11"

# command
cloud = "2.0.0-beta.2"

# utilities
immutables = "2.9.2"
geantyref = "1.3.15"

# testing
junit = "5.10.1"
assert4j = "3.25.1"

# static analysis
jspecify = "0.3.0"
errorprone-gradle = "3.1.0"
errorprone-core = "2.24.1"
nullaway = "0.10.21"

# linting
palantir = "2.39.0"
ktlint = "0.49.1"

# gradle
toxopid = "3.2.0"
indra = "3.1.3"
spotless = "6.24.0"
shadow = "8.1.1"
mammoth = "1.3.1"

[libraries]

# mindustry
mindustry-core = { module = "com.github.Anuken.Mindustry:core", version.ref = "mindustry" }
mindustry-server = { module = "com.github.Anuken.Mindustry:server", version.ref = "mindustry" }
arc-core = { module = "com.github.Anuken.Arc:arc-core", version.ref = "mindustry" }
arc-backend-headless = { module = "com.github.Anuken.Arc:backend-headless", version.ref = "mindustry" }

# logging
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-from-jul = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }

# command
cloud-core = { module = "org.incendo:cloud-core", version.ref = "cloud" }

# utilities
immutables = { module = "org.immutables:value", version.ref = "immutables" }
geantyref = { module = "io.leangen.geantyref:geantyref", version.ref = "geantyref" }

# testing
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
assert4j-core = { module = "org.assertj:assertj-core", version.ref = "assert4j" }

# static analysis
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
errorprone-gradle = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version.ref = "errorprone-gradle" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone-core" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }

# gradle
toxopid = { module = "fr.xpdustry:toxopid", version.ref = "toxopid" }
indra-common = { module = "net.kyori:indra-common", version.ref = "indra" }
indra-licenser-spotless = { module = "net.kyori:indra-licenser-spotless", version.ref = "indra" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
shadow = { module = "com.github.johnrengelman:shadow", version.ref = "shadow" }
mammoth = { module = "net.kyori:mammoth", version.ref = "mammoth" }

[bundles]
indra = [ "indra-common", "indra-licenser-spotless" ]
tests = [ "junit-api", "junit-engine", "assert4j-core" ]
mindustry = [ "mindustry-core", "mindustry-server", "arc-core", "arc-backend-headless" ]