ranks:
  mindustry_player:
    distributor.player.lookup.name: true
    distributor.player.lookup.entity_id: true
    distributor.player.lookup.server_id: true
  mindustry_admin:
    distributor.player.lookup.uuid: true
