name: Build

on: [
    push,
    pull_request,
    workflow_dispatch
]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Build artifacts
        id: build
        run: |
          chmod +x ./gradlew
          ./gradlew jar
          echo '::set-output name=ARTIFACT_PATH::'$(./gradlew getArtifactPath -q)

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Distributor-core
          path: ${{ steps.build.outputs.ARTIFACT_PATH }}
