name: Commit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Build artifacs
        id: build
        run: |
          ./gradlew build
          echo '::set-output name=ARTIFACT_CORE_PATH::'$(./gradlew distributor-core:getArtifactPath -q)
          echo '::set-output name=ARTIFACT_SCRIPT_JS_PATH::'$(./gradlew distributor-js:getArtifactPath -q)

      - name: Upload distributor-core
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ steps.build.outputs.ARTIFACT_CORE_PATH }}

      - name: Upload distributor-js
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ steps.build.outputs.ARTIFACT_SCRIPT_JS_PATH }}

      - name: Publish snapshot to Xpdustry
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_xpdustryUsername: "${{ secrets.XPDUSTRY_REPO_USERNAME }}"
          ORG_GRADLE_PROJECT_xpdustryPassword: "${{ secrets.XPDUSTRY_REPO_PASSWORD }}"
