name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Build artifacs
        run: ./gradlew build

      - name: Set up the release
        id: release
        run: |
          tag=$(cat plugin.json | grep "version*")          # Cut the line with the version in plugin.json
          tag=$(echo $tag | cut -d ":" -f 2,3)              # Split with ":" and take the version number
          tag=$(echo $tag | tr -d \"," ")                   # Trim the " and , and spaces
          echo '::set-output name=RELEASE_TAG::'$tag        # Set the environment variable

          echo '::set-output name=ARTIFACT_CORE_PATH::'$(./gradlew distributor-core:getArtifactPath -q)
          echo '::set-output name=ARTIFACT_SCRIPT_JS_PATH::'$(./gradlew distributor-js:getArtifactPath -q)

      - name: Set up the changelog
        id: changelog
        shell: bash
        run: |
          r=$(cat CHANGELOG.md)
          r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "::set-output name=CHANGELOG::$r"

      - name: Upload distributor-core
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: v${{ steps.release.outputs.RELEASE_TAG }} release
          body: ${{ steps.changelog.outputs.CHANGELOG }}

          asset_name: ${{ github.event.repository.name }}-core.jar
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.release.outputs.ARTIFACT_CORE_PATH }}
          tag: v${{ steps.release.outputs.RELEASE_TAG }}

      - name: Upload distributor-js
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: ${{ github.event.repository.name }}-js.jar
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.release.outputs.ARTIFACT_SCRIPT_JS_PATH }}
          tag: v${{ steps.release.outputs.RELEASE_TAG }}

      - name: Publish release to Xpdustry
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_xpdustryUsername: "${{ secrets.XPDUSTRY_REPO_USERNAME }}"
          ORG_GRADLE_PROJECT_xpdustryPassword: "${{ secrets.XPDUSTRY_REPO_PASSWORD }}"
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.XPDUSTRY_SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.XPDUSTRY_SIGNING_PASSWORD }}"
